### ISSUE TITLE
Add support for vNext Builds

### ISSUE THREAD

**Issue by jelledruyts** [jelledruyts/TfsTeamProjectManager#1]
From an administration perspective, I think it would be useful to be able to mass upload a build template to selected projects. 

Also, it would probably also be useful to get/modify all builds for selected projects and various attributes, such as drop locations, default build queue, etc.

**Comment by soccerjoshj07** [comment]
I'm the original requester of this feature - I still think it would be super useful! https://teamprojectmanager.codeplex.com/discussions/651234

**Comment by jelledruyts** [comment]
And I still agree! It's just a question of having time to dig in to the new API's and coding it up. You're always free to submit a pull request if you have the time of course :-)

**Comment by jelledruyts** [comment]
I've started implementing the module for vNext builds and am currently planning on supporting bulk update of the following properties: Build Number Format, Path (i.e. build folder) and Queue.

Are there other things you would want to update? I'm not planning on updating anything inside the task steps themselves as that would be very brittle, so only base properties of the build definition itself.

**Comment by jelledruyts** [comment]
Updating the Queue will have to wait a bit as a required part of the API is still in preview. See #15.

**Comment by soccerjoshj07** [comment]
What about adding some of the repository or trigger settings? I could see it beneficial to mass update (or even just view) some of those properties; label format, repository, or whether or not this is a continuous deployment build for example. 

Also, do you have any plans for adding a Release module in the future? I could see that being incredibly useful as well.

**Comment by jelledruyts** [comment]
The repository will already be shown in the grid. The problem with most other properties is that they're lists, e.g. you can't just say "it's a CI build" because there is a _list_ of build triggers (CI, scheduled, gated, ...). I could add a column to the overview grid that contains all trigger types, but not much more as it would make the grid unreadable I think.

Bulk update would similarly be quite tricky as you'd have to build some UI to define the trigger type(s) you want to apply to all selected build definitions - and probably by overwriting any existing triggers first. So all in all, I don't see a nice clean solution at this point in time. Of course feel free to create issues for individual features like that and we can discuss further if you have ideas.

And yes, Releases will also be supported but I'm waiting for the final client API's for that (see the other open issues).

**Comment by jelledruyts** [comment]
See #16 for the build triggers, which I definitely think is doable in some meaningful way.
