### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by rerime** [jelledruyts/TfsTeamProjectManager#20]
Does it work with TFS 2017 Update1 with [new form](https://www.visualstudio.com/en-us/docs/work/process/new-work-item-experience)?
And where I can get already built TfsTeamProjectManager?

**Comment by jelledruyts** [comment]
The new form should not have an impact since the XML files are the same. If there would be a problem anyway, please log a new issue.

You can find the binaries under https://github.com/jelledruyts/TfsTeamProjectManager/releases.

**Comment by rerime** [comment]
Thank you!
