### ISSUE TITLE
Add support for managing "global lists"

### ISSUE THREAD

**Issue by Styxxy** [jelledruyts/TfsTeamProjectManager#27]
Add the feature to manage global lists of a Collection in TFS (https://docs.microsoft.com/en-us/vsts/work/customize/reference/define-global-lists).

**Comment by jelledruyts** [comment]
Sorry, that doesn't fall within the scope of the tool which is to automate actions across multiple Team Projects. You can manage global lists via the command line or in Visual Studio using the "TFS Process Template Editor" or TFS Power Tools extensions. See https://docs.microsoft.com/en-us/vsts/work/customize/reference/witadmin/manage-global-lists-for-work-item-types.

**Comment by mesheets** [comment]
On the webpage at the that link @jelledruyts provided, there is the following statement in one of the green-highlighted "Tip" blocks:
> Or, you can use the [TFS Team Project Manager](https://github.com/jelledruyts/TfsTeamProjectManager), an open-source client available from GitHub.

I came here directly from that aforementioned docs.microsoft.com web page in search of such functionality, too.  As Global List command line management is handled by witadmin (just like many other capabilities handled by TFS Team Project Manager), and as Global Lists can be specified and used in Work Item Type Definitions, it would be handy to have all of that in a single, lightweight tool.


At any rate, at a minimum it would appear that some type of clarification might need to be provided to docs.microsoft.com, as apparently those documenters were expecting such witadmin functionality to exist in TFS Team Project manager, too….
