### ISSUE TITLE
This version broke custom work item export for me

### ISSUE THREAD

**Issue by pamurp7789** [jelledruyts/TfsTeamProjectManager#3]
Using version 2.0.5885, I have no problem exporting Work Item Configuration > Work Item Types > Custom work items.  When using the latest version 2.1.6180, the custom work item types no longer appear in the list when I click 'Get Work Item Types'.

**Comment by pamurp7789** [comment]
Sorry I would like to add that this is using VSO.

**Comment by jelledruyts** [comment]
I've just noticed the same today against TFS 2015 Update 3, I'm investigating.

**Comment by jelledruyts** [comment]
I cannot reproduce the issue on another TFS 2015 Update 3 server, so it seems to be related to the environment.

I won't have access to yesterday's server where I can repro the problem for at least two weeks, so could you quickly try something in your environment? Can you clear the local TFS cache by removing (or renaming) the `%LOCALAPPDATA%\Microsoft\Team Foundation\6.0\Cache` folder?

**Comment by pamurp7789** [comment]
Deleted that folder, restarted TfsTeamProjectManager, and issue still persists. All standard work item types return but no custom ones appear.

**Comment by jelledruyts** [comment]
Ah, I see , this is probably something else than what I had noticed: I was getting an "API resource location 8637ac8b-5eb6-4f90-b3f7-4f2ff576a459 is not registered" error and did not get any work items back.

But I assume that you're not getting an error, it's just that _custom_ work item types do not get returned, right? Or if you are seeing an error can you copy it here? (Click on the task link on the top of the window to open the task details if needed, or open the log file.)

**Comment by pamurp7789** [comment]
Correct, there are no errors that appear (and the log is quite empty, just showing start/end).

I did a little bit of troubleshooting and found the following differences between the two programs (Using Fiddler).

1. Version 2.0.5885 says "connected to tfs 2015" when I select my VSO project.  Version 2.1.6180 says "connected to tfs 2017"
2. The request api being used is different.  Version 2.0.5885 is calling "https://<vsoproject>.visualstudio.com/<vsoproject>/_apis/ " while Version 2.1.6180 is calling "https://<vsoproject>.visualstudio.com/<guid>/_apis/wit/workItemTypeTemplate/<CustomWorkItemType>?exportGlobalLists=False "
3. Finally, the biggest red flag I see is a 400 Bad Request result when querying for the custom work item in Version 2.1.6180 (this doesn't happen in the other version).  Sample request/response below.

Hopefully this gives you more ideas on where to dig into to.

Thanks,
Patrick

Request:
GET https://<projectname>.visualstudio.com/<guid>/_apis/wit/workItemTypeTemplate/<customworkitemtype>?exportGlobalLists=False HTTP/1.1
Accept: application/json; api-version=2.3-preview.1
User-Agent: VSServices/14.102.25423.0 (TeamProjectManager.exe)
Accept-Language: en-US
X-TFS-FedAuthRedirect: Suppress
X-TFS-Session: <guid>
Cookie: FedAuth=<token>
FedAuth1=<token>
Host: <projectname>.visualstudio.com
Accept-Encoding: gzip

Response
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-TFS-ProcessId: <guid>
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-FRAME-OPTIONS: SAMEORIGIN
X-VSS-UserData: <guid>:<username>
ActivityId: <guid>
X-TFS-Session: <guid>
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
X-Content-Type-Options: nosniff
Date: Wed, 07 Dec 2016 18:16:36 GMT
Content-Length: 274

{"$id":"1","innerException":null,"message":"VS403207: The object does not exist or access is denied.","typeName":"System.ArgumentException, mscorlib, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","typeKey":"ArgumentException","errorCode":0,"eventId":0}

**Comment by jelledruyts** [comment]
Sorry for the delay but I was able to clear it up with the product group. Unfortunately exporting custom work item types in the new customization system (the web access-based UI as opposed to the traditional XML based system) is not currently supported. It's actually an unfortunate side effect that it used to work in VSTS, but it should not have worked.

So for now, you can only export work item types from on-premise TFS projects (that are not using the new system yet). They are working on new REST API's that will support the same scenario for the new system and when that's available I'll update the tool.
