### ISSUE TITLE
Cannot retrieve any build definitions

### ISSUE THREAD

**Issue by vitormota** [jelledruyts/TfsTeamProjectManager#4]
For TFS on premises Version 14.102.25423.0

Always retrieve 0 build definitions although I have at least 5 defined, permissions issue? Both Project and Build Admin

**Comment by jelledruyts** [comment]
Are you referring to XAML Build Definitions or the task-based (vNext) build definitions? Only the XAML ones are supported for now, which would explain why you're not seeing any.

**Comment by vitormota** [comment]
Must have missed that information somewhere, closing issue.

**Comment by jelledruyts** [comment]
See https://github.com/jelledruyts/TfsTeamProjectManager/issues/1 :-)
