### ISSUE TITLE
Add support for custom work item types in VSTS

### ISSUE THREAD

**Issue by gbaytler** [jelledruyts/TfsTeamProjectManager#6]
I created custom work item type in VSTS inherited from Scrum system process, but I do not see it in the list of work item types in TfsTeamProjectManager, yet it is listed in Categories.

**Comment by jelledruyts** [comment]
Custom work item types in the new "inherited" model in VSTS is not yet supported. See https://github.com/jelledruyts/TfsTeamProjectManager/issues/3 for more details.
